# Generated by Django 5.2 on 2025-04-30 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='image',
        ),
        migrations.CreateModel(
            name='ReceiptImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='receipt_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='receipts.receipt')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
