# Generated by Django 5.2 on 2025-05-31 11:10

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_alter_product_receipt_alter_receipt_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='warranty_months',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receiptimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
