# Generated by Django 5.2 on 2025-05-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_alter_receipt_warranty_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='category',
            field=models.CharField(choices=[('food', 'Храна'), ('electronics', 'Електроника'), ('clothing', 'Дрехи'), ('home', 'Дом'), ('pharmacy', 'Аптека'), ('transport', 'Транспорт'), ('entertainment', 'Развлечения'), ('education', 'Образование'), ('utilities', 'Сметки'), ('services', 'Услуги'), ('finances', 'Финанси'), ('other', 'Друго')], max_length=50),
        ),
    ]
